### ISSUE TITLE
Is Vue compatible with SystemJS?

### ISSUE THREAD

**Issue by thelinuxlich** [yyx990803/vue#1087]
I'm getting this error:

```
debug.js:13 [Vue warn]: Invalid template option: [object Object]
es6-module-loader.src.js:140 Potentially unhandled rejection [2] TypeError: Cannot set property '__vue__' of undefined
    at VueComponent.exports._initElement (http://127.0.0.1:8080/jspm_packages/npm/vue@0.12.8/src/instance/compile.js:47:20)
    at VueComponent.exports._compile (http://127.0.0.1:8080/jspm_packages/npm/vue@0.12.8/src/instance/compile.js:14:10)
    at VueComponent.exports.$mount (http://127.0.0.1:8080/jspm_packages/npm/vue@0.12.8/src/api/lifecycle.js:14:10)
    at VueComponent.exports._init (http://127.0.0.1:8080/jspm_packages/npm/vue@0.12.8/src/instance/init.js:34:10)
    at new VueComponent (eval at createClass (unknown source), <anonymous>:1:47)
    at Vue.exports.$addChild (http://127.0.0.1:8080/jspm_packages/npm/vue@0.12.8/src/api/child.js:26:15)
    at Directive.module.exports.build (http://127.0.0.1:8080/jspm_packages/npm/vue@0.12.8/src/directives/component.js:93:28)
    at Directive.module.exports.initStatic (http://127.0.0.1:8080/jspm_packages/npm/vue@0.12.8/src/directives/component.js:31:24)
    at exports.bind (http://127.0.0.1:8080/jspm_packages/npm/vue@0.12.8/src/util/lang.js:134:12)
    at http://127.0.0.1:8080/jspm_packages/npm/vue@0.12.8/src/directives/component.js:73:9(anonymous function) @ es6-module-loader.src.js:140f @ es6-module-loader.src.js:167i @ es6-module-loader.src.js:189
```

Templates are loaded like this:

```
{
   template: System.import("./index.html!text")
}
```

**Comment by yyx990803** [comment]
The return value of `System.import` is a Promise. This is a runtime API, I don't think you should be using it for splitting up component files.

**Comment by thelinuxlich** [comment]
I think the template option should accept a Promise exactly for this use case

**Comment by thelinuxlich** [comment]
because even if I write "import template from "index.html!text" it will return a promise if I didn't build it

**Comment by rpkilby** [comment]
Hi! We've been using Vue.js in an ES6/SystemJS environment for a little while. The key is to write your modules using the standard es6 syntax, then use `System.import` to load the main Vue module. It doesn't require bundling or any other complexities. The setup should look something like the following:

```javascript
// some/component.js
import Vue from 'vue';
import template from 'path/to/template.html!text';


const SomeComponent = Vue.extend({
    template: template,
    ...
});

export default SomeComponent;
```

```javascript
// some/vue.js
import Vue from 'vue';
import SomeComponent from 'some/component';

Vue.component('some-component', SomeComponent);

new Vue({
    ...
});
```

The html served to the client includes the following bits:
```html
...
<script src="system.js"></script>
<script src="config.js"></script>
<script>
     System.import('some/vue');
</script>
...
```

Let me know if there's anything that can be better articulated.

**Comment by thelinuxlich** [comment]
I was doing like your tip, but this will only work if I always build the final script on every change

**Comment by rpkilby** [comment]
> I was doing like your tip, but this will only work if I always build the final script on every change

Is this a browser caching issue? If the bundle path/name changes per build, then that would get around the caching. The individual module paths are static however, so your browser would be caching old versions of your files.

**Comment by divmgl** [comment]
Hey @thelinuxlich, were you able to make this work? 

I've basically switched to using the SystemJS builder and have started building self executing bundles. With Vue, I'm doing something similar to this:

```js
var template = require("template.html!text");

var component = Vue.extend({
  template: template
});

Vue.component('app', component);

new Vue({
  el: '#app'
});
```

**Comment by thelinuxlich** [comment]
No, I moved to Webpack

**Comment by guilhermeaiolfi** [comment]
No movement to bring vuejs singe file components to JSPM world yet?

**Comment by lgdexter** [comment]
https://github.com/vuejs/systemjs-plugin-vue looks like @yyx990803 is looking into making a System.js plugin for Vue components.

**Comment by sant123** [comment]
I just made an example for this https://github.com/sant123/testing-systemjs-vue

**Comment by ziyuang** [comment]
@sant123 Your link gives a 404 error.

**Comment by sant123** [comment]
Yes @ziyuang, I removed it some days ago.... I encourage you to use Webpack, the performance between this and SystemJS is really high!
